name: upimapi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - pandas <=1.3.0
    - diamond
    - psutil
    - tqdm
    - requests
    - biopython =1.78
    - selenium
    - firefox
    - lxml
    - geckodriver
    - pyyaml