name: upimapi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - pandas
    - diamond
    - psutil
    - tqdm
    - requests
    - biopython
    - selenium
    - firefox
    - lxml
    - geckodriver