name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: upimapi:latest
          outputs: type=docker,dest=/tmp/upimapi.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: upimapi
          path: /tmp/upimapi.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: upimapi
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/upimapi.tar
          docker image ls -a

      - name: Check base entrypoint
        run: docker run upimapi /bin/bash -c "ls"

      - name: IDs inputted through TXT file (comma-separated)
        run: docker run upimapi /bin/bash -c "upimapi -i UPIMAPI/ci/ids.csv -rd resources_directory --no-annotation -cols 'Entry&KEGG&Interacts with'"

      - name: Full IDs inputted through TXT file (newline-separated)
        run: docker run upimapi /bin/bash -c "upimapi -i UPIMAPI/ci/full_ids.txt -rd resources_directory --no-annotation"

      - name: IDs inputted through BLAST file
        run: docker run upimapi /bin/bash -c "upimapi -i UPIMAPI/ci/ids.blast -rd resources_directory --no-annotation --blast"

      - name: Obtain FASTA sequences
        run: docker run upimapi /bin/bash -c "upimapi -i UPIMAPI/ci/ids.csv -rd resources_directory --no-annotation --fasta"

      - name: Full workflow, TaxIDs DB at Species level
        run: docker run upimapi /bin/bash -c "upimapi -i UPIMAPI/ci/proteomes.fasta -rd resources_directory -db taxids --taxids 2203,2223,2209,2162,119484,35554,29543,863"
